name: bitarena
description: "Project Flutter Store Games."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.12.0
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_fonts: ^6.3.2
  google_sign_in: ^6.2.1
  injectable: ^2.3.2
  loading_animation_widget: ^1.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_login.png
    - assets/amine.jpeg
